apiVersion: v1
kind: ReplicationController
metadata:
    name: kubia
spec:
    replicas: 3
    selector:
        app: kubia

    template:
        metadata:
            labels:
                app: kubia

        spec:
          containers:
            - name: kubia
              image: ericw16/kubia
              ports:
                 - containerPort: 8080
