apiVersion: v1
kind: Pod
metadata:
    name: kubia-unhealthy
spec:
    containers:
        - image: ericw16/kubia-unhealthy
          name: kubia
          livenessProbe:
              httpGet:
                  path: /
                  port: 8080
